### ISSUE TITLE
c.readStringArg() error

### ISSUE THREAD

**Issue by joshuakaleb0424** [harmsm/PyCmdMessenger#28]
error: array must be initialized with a brace-enclosed initializer
     char arr[128] = c.readStringArg();

**Comment by joshuakaleb0424** [comment]
Fixed it. 
`char* saw = c.readStringArg();`

Another question. Is there a limit to how long a string I can send?

**Comment by harmsm** [comment]
Hmm.  I'm not entirely sure, but I think you'll be limited by the memory on
the arduino rather than anything in the messenger.  The length of string
will not be limited by the python side.  From what I understand of the
ArduinoCmdMessenger library, there shouldn't be a limit.  It might be
interesting to send longer and longer stings to see what happens...

Mike


On Sun, Feb 26, 2017 at 6:47 PM joshuakaleb0424 <notifications@github.com>
wrote:

Fixed it.
char* saw = c.readStringArg();

Another question. Is there a limit to how long a string I can send?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/harmsm/PyCmdMessenger/issues/28#issuecomment-282615102>,
or mute the thread
